# This is free software, licensed under the GNU General Public License v2.

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for local event notifications
LUCI_DEPENDS:=+luci-base +curl +ca-bundle +comgt +luci-app-quectel-cm
PKG_LICENSE:=GPL-2.0-only
PKG_MAINTAINER:=Shiva Aradi <developer.aradi@gmail.com>

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
