#
# This is free software, licensed under the GNU General Public License v2.

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for Internet Health Daemon
LUCI_DEPENDS:=+luci-base +jsonfilter
PKG_LICENSE:=GPL-2.0-only
PKG_MAINTAINER:=Shiva Aradi <developer.aradi@gmail.com>

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
