#!/bin/sh /etc/rc.common

START=98
STOP=10
USE_PROCD=1

NAME=qtcmsim-failover
PROG=/usr/libexec/qtcmsim-failover

start_service() {
	local enabled

	config_load qtcm
	config_get_bool enabled failover enabled 0
	[ "$enabled" = "1" ] || {
		logger -t "$NAME" "service disabled in qtcm.failover.enabled"
		return 0
	}

	procd_open_instance "$NAME"
	procd_set_param command "$PROG"
	procd_set_param respawn 3600 5 5
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger "qtcm"
}
