#!/bin/sh /etc/rc.common

START=95
STOP=10
USE_PROCD=1

service_enabled() {
	[ "$(uci -q get internet-healthd.main.enabled)" = "1" ]
}

start_service() {
	service_enabled || return 0

	procd_open_instance
	procd_set_param command /usr/sbin/internet-healthd
	procd_set_param respawn 3600 5 5
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

reload_service() {
	stop
	start
}

service_triggers() {
	procd_add_reload_trigger internet-healthd firewall network
}
