#!/bin/sh

uci -q get device_mode.main >/dev/null && exit 0

uci -q batch <<'EOF'
set device_mode.main='config'
set device_mode.main.mode='router'
set device_mode.main.lan_ipaddr='192.168.1.1'
set device_mode.main.lan_netmask='255.255.255.0'
set device_mode.main.wan_ifname='wan'
set device_mode.main.lan_ifname='lan'
set device_mode.main.wifi_radio='radio0'
set device_mode.main.ap_ssid='OpenWrt'
set device_mode.main.ap_encryption='none'
set device_mode.main.uplink_encryption='psk2'
set device_mode.main.dumb_lan_proto='static'
commit device_mode
EOF

exit 0
