#!/bin/sh

set_default() {
	local option="$1"
	local value="$2"

	uci -q get "$option" >/dev/null || uci -q set "$option=$value"
}

add_default_list() {
	local option="$1"
	local value="$2"

	uci -q show "$option" | grep -qx ".*='$value'" || uci -q add_list "$option=$value"
}

uci -q get qtcm.main >/dev/null || uci -q set qtcm.main='qtcm'
set_default qtcm.main.enabled '0'
set_default qtcm.main.active_sim '1'

uci -q get qtcm.sim1 >/dev/null || uci -q set qtcm.sim1='sim'
set_default qtcm.sim1.enabled '1'
set_default qtcm.sim1.apn 'internet'
set_default qtcm.sim1.network_mode 'auto'
set_default qtcm.sim1.ip_type 'ipv4'
set_default qtcm.sim1.use_dns '1'

uci -q get qtcm.sim2 >/dev/null || uci -q set qtcm.sim2='sim'
set_default qtcm.sim2.enabled '0'
set_default qtcm.sim2.network_mode 'auto'
set_default qtcm.sim2.ip_type 'ipv4'
set_default qtcm.sim2.use_dns '1'

uci -q get qtcm.failover >/dev/null || uci -q set qtcm.failover='failover'
set_default qtcm.failover.enabled '0'
set_default qtcm.failover.priority_1 'internet'
set_default qtcm.failover.priority_2 'rssi'
set_default qtcm.failover.priority_3 'latency'
set_default qtcm.failover.priority_4 'quota'
set_default qtcm.failover.priority_5 'snr'
set_default qtcm.failover.check_internet_failure '1'
set_default qtcm.failover.check_signal_strength '1'
set_default qtcm.failover.switch_above_signal '75'
set_default qtcm.failover.check_snr '0'
set_default qtcm.failover.minimum_snr '5'
set_default qtcm.failover.flap_wait '300'
set_default qtcm.failover.enable_network_reboot '0'
set_default qtcm.failover.reboot_on_network_loss '1800'
set_default qtcm.failover.check_ping_status '0'
add_default_list qtcm.failover.ping_ipv4_ips '139.59.0.25'
add_default_list qtcm.failover.ping_ipv4_ips '8.8.8.8'
add_default_list qtcm.failover.ping_ipv4_ips '1.1.1.1'
set_default qtcm.failover.minimum_responses '1'
set_default qtcm.failover.minimum_ping_responses '1'
set_default qtcm.failover.response_timeout '10'
set_default qtcm.failover.check_link_performance '0'
set_default qtcm.failover.failure_latency '450'
set_default qtcm.failover.acceptable_latency '200'
set_default qtcm.failover.check_data_usage '0'
set_default qtcm.failover.sim1_quota_day '2'
set_default qtcm.failover.sim2_quota_day '2'
set_default qtcm.failover.link_check_interval '180'
set_default qtcm.failover.restart_qtcm_after_switch '1'
set_default qtcm.failover.post_switch_hook '/etc/qtcm_custom_failover_script.sh'

uci -q commit qtcm

exit 0
