#!/bin/sh

# Remove stale Lua dispatcher files from older builds. The app now uses
# menu.d JSON entries and JS views under /www/luci-static/resources/view/.
rm -f /usr/lib/lua/luci/controller/quectel_cm.lua
rm -f /usr/lib/lua/luci/view/quectel_cm/config.htm
rm -f /tmp/luci-indexcache.*
rm -rf /tmp/luci-modulecache/

set_default() {
	local option="$1"
	local value="$2"

	uci -q get "$option" >/dev/null || uci -q set "$option=$value"
}

add_default_list() {
	local option="$1"
	local value="$2"

	uci -q show "$option" | grep -qx ".*='$value'" || uci -q add_list "$option=$value"
}

uci -q get qtcm.main >/dev/null || uci -q set qtcm.main='qtcm'
set_default qtcm.main.enabled '0'
set_default qtcm.main.active_sim '1'

uci -q get qtcm.sim1 >/dev/null || uci -q set qtcm.sim1='sim'
set_default qtcm.sim1.enabled '1'
set_default qtcm.sim1.apn 'internet'
set_default qtcm.sim1.network_mode 'auto'
set_default qtcm.sim1.ip_type 'ipv4'
set_default qtcm.sim1.use_dns '1'

uci -q get qtcm.sim2 >/dev/null || uci -q set qtcm.sim2='sim'
set_default qtcm.sim2.enabled '0'
set_default qtcm.sim2.network_mode 'auto'
set_default qtcm.sim2.ip_type 'ipv4'
set_default qtcm.sim2.use_dns '1'

uci -q get qtcm.sim_switch >/dev/null || uci -q set qtcm.sim_switch='sim_switch'
set_default qtcm.sim_switch.mode 'gpio'
set_default qtcm.sim_switch.sim1_value '1'
set_default qtcm.sim_switch.sim2_value '0'
set_default qtcm.sim_switch.command 'AT+QDSIM'
set_default qtcm.sim_switch.power_cycle_mpcie '1'

uci -q get qtcm.failover >/dev/null || uci -q set qtcm.failover='failover'
set_default qtcm.failover.enabled '0'
set_default qtcm.failover.priority_1 'internet'
set_default qtcm.failover.priority_2 ''
set_default qtcm.failover.priority_3 ''
set_default qtcm.failover.priority_4 ''
set_default qtcm.failover.priority_5 ''
set_default qtcm.failover.check_internet_failure '1'
set_default qtcm.failover.check_signal_strength '0'
set_default qtcm.failover.switch_above_signal '75'
set_default qtcm.failover.check_snr '0'
set_default qtcm.failover.minimum_snr '5'
set_default qtcm.failover.flap_wait '5'
set_default qtcm.failover.enable_network_reboot '0'
set_default qtcm.failover.reboot_on_network_loss '500'
set_default qtcm.failover.check_ping_status '0'
add_default_list qtcm.failover.ping_ipv4_ips '8.8.8.8'
add_default_list qtcm.failover.ping_ipv4_ips '1.1.1.1'
set_default qtcm.failover.minimum_responses '1'
set_default qtcm.failover.minimum_ping_responses '1'
set_default qtcm.failover.response_timeout '3'
set_default qtcm.failover.check_link_performance '0'
set_default qtcm.failover.failure_latency '450'
set_default qtcm.failover.acceptable_latency '200'
set_default qtcm.failover.check_data_usage '0'
set_default qtcm.failover.sim1_quota_day '2'
set_default qtcm.failover.sim2_quota_day '2'
set_default qtcm.failover.link_check_interval '10'
set_default qtcm.failover.post_switch_settle_time '50'
set_default qtcm.failover.restart_qtcm_after_switch '1'
set_default qtcm.failover.post_switch_hook '/etc/qtcm_custom_failover_script.sh'
set_default qtcm.failover.primary_sim '1'
set_default qtcm.failover.backup_sim '2'
set_default qtcm.failover.enable_primary_failback '0'
set_default qtcm.failover.primary_retry_interval '300'
set_default qtcm.failover.primary_retry_settle_time '60'
set_default qtcm.failover.primary_retry_check_internet '1'

uci -q get qtcm.troubleshoot >/dev/null || uci -q set qtcm.troubleshoot='troubleshoot'
set_default qtcm.troubleshoot.check_sim_error '1'
set_default qtcm.troubleshoot.check_modem_response '1'
set_default qtcm.troubleshoot.check_interface_ip '1'
set_default qtcm.troubleshoot.check_registration '1'
set_default qtcm.troubleshoot.check_ping '1'
set_default qtcm.troubleshoot.sim_error_fail_count '2'
set_default qtcm.troubleshoot.modem_response_fail_count '2'
set_default qtcm.troubleshoot.interface_ip_fail_count '2'
set_default qtcm.troubleshoot.registration_fail_count '2'
set_default qtcm.troubleshoot.ping_fail_count '2'
set_default qtcm.troubleshoot.recovery_settle_time '60'
set_default qtcm.troubleshoot.action_1 'restart_qtcm'
set_default qtcm.troubleshoot.action_2 'power_cycle_mpcie'
set_default qtcm.troubleshoot.action_3 'switch_sim'
set_default qtcm.troubleshoot.action_4 'reboot_router'
set_default qtcm.troubleshoot.action_5 ''
set_default qtcm.troubleshoot.sim_error_action_1 ''
set_default qtcm.troubleshoot.sim_error_action_2 ''
set_default qtcm.troubleshoot.sim_error_action_3 ''
set_default qtcm.troubleshoot.sim_error_action_4 ''
set_default qtcm.troubleshoot.sim_error_action_5 ''
set_default qtcm.troubleshoot.modem_response_action_1 ''
set_default qtcm.troubleshoot.modem_response_action_2 ''
set_default qtcm.troubleshoot.modem_response_action_3 ''
set_default qtcm.troubleshoot.modem_response_action_4 ''
set_default qtcm.troubleshoot.modem_response_action_5 ''
set_default qtcm.troubleshoot.interface_ip_action_1 ''
set_default qtcm.troubleshoot.interface_ip_action_2 ''
set_default qtcm.troubleshoot.interface_ip_action_3 ''
set_default qtcm.troubleshoot.interface_ip_action_4 ''
set_default qtcm.troubleshoot.interface_ip_action_5 ''
set_default qtcm.troubleshoot.registration_action_1 ''
set_default qtcm.troubleshoot.registration_action_2 ''
set_default qtcm.troubleshoot.registration_action_3 ''
set_default qtcm.troubleshoot.registration_action_4 ''
set_default qtcm.troubleshoot.registration_action_5 ''
set_default qtcm.troubleshoot.ping_action_1 ''
set_default qtcm.troubleshoot.ping_action_2 ''
set_default qtcm.troubleshoot.ping_action_3 ''
set_default qtcm.troubleshoot.ping_action_4 ''
set_default qtcm.troubleshoot.ping_action_5 ''

uci -q commit qtcm

exit 0
