#!/bin/sh

if [ "$PKG_UPGRADE" != 1 ]; then
	uci get luci.themes.AnexGateSimplified >/dev/null 2>&1 || \
	uci batch <<-EOF
		set luci.themes.AnexGateSimplified=/luci-static/anexgate-simplified
		set luci.main.mediaurlbase=/luci-static/anexgate-simplified
		commit luci
	EOF
fi

exit 0
